### ISSUE TITLE
RV1 is not well described.I have not found a description of its purpose, nor of the method to determine correct setting.

### ISSUE THREAD

**Issue by riwide** [skiselev/Z80-512K#1]
It would help understand and diagnose, to know more about RV1.
Why is it needed and how should I set its value?

I have parts and PCB on order to construct an Z80-512K board.

**Comment by skiselev** [comment]
I've added the following note to the [Assembly Instructions](https://github.com/skiselev/Z80-512K/blob/main/Assembly_Instructions.md):

*Note:* The Z80-512K can generate NMI interrupts to the CPU when power failure is detected. The RV1 trimmer resistor is used to fine tune the power failure threshold voltage. It is normally safe to set it to a middle position. If using the NMI on power failure feature, the RV1 can be adjusted by setting the board power supply to the desired power failure voltage (for example, 4.5 V), and adjusting the resistor until the /PFO output (pin 10) of U5 goes low.

Let me know if you think it sufficiently clarifies the purpose of RV1

**Comment by riwide** [comment]
Thanks, makes sense now. I will know more once I have it built and running.

Cheers

Richard
